### ISSUE TITLE
Oneclick payment

### ISSUE THREAD

**Issue by Otaznicek** [litteratum/csobpg#4]
Hello,

I am currently working on integrating the ČSOB payment gateway into our application and I am interested in implementing the OneClick payment feature. However, I am not sure if this feature is fully supported in the current version of the API provided by this library.

Could you please provide some guidance or examples on how to set up and process OneClick payments using this library? Specifically, I would like to understand:

1. How to initialize a payment that saves the customer's payment information for future OneClick transactions.
2. How to use the saved payment information (token) for subsequent OneClick payments.
3. Any specific API methods or endpoints required for these processes.

Thank you for your assistance.

Best regards,
Matyas Auervek

**Comment by litteratum** [comment]
@Otaznicek, Greetings. The library currently supports only basic methods.
But yes, I believe we can add OneClick payment.

I'll check it today and let you know.
